const IS_LOADING_AUTH = 'IS_LOADING_AUTH';
const USER_DATA = 'USER_DATA';
const ACCOUNT_TYPE = 'ACCOUNT_TYPE';
const LOGIN_USER = 'LOGIN_USER';
const OTP_SEND = 'OTP_SEND';
const VERIFY_EMAIL = 'VERIFY_EMAIL';
const SPECIALIST_FORM = 'SPECIALIST_FORM';

export { IS_LOADING_AUTH, USER_DATA, ACCOUNT_TYPE,LOGIN_USER,OTP_SEND,VERIFY_EMAIL, SPECIALIST_FORM };